version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_host
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-book_manager}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres_network

volumes:
  db_data:

networks:
  postgres_network:
    driver: bridge
